[package]
name = "multi_tree"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
draw_backend_recording = { workspace = true }
draw_components = { workspace = true }
draw_core = { workspace = true }
draw_render = { workspace = true }
draw_scene = { workspace = true }
draw_theme = { workspace = true }
draw_ui = { workspace = true }
