[package]
name = "draw_components"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
draw_core.workspace = true
draw_ui.workspace = true
draw_render.workspace = true
draw_theme.workspace = true

[dev-dependencies]
draw_backend_recording.workspace = true
