[package]
name = "web_demo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
draw_core.workspace = true
draw_render.workspace = true
draw_scene.workspace = true
draw_ui.workspace = true
draw_wasm.workspace = true
demo_app.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["Window", "Document", "Element", "HtmlElement"] }
